config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'blogs#index'
  resources :blogs , only:[:create,:destroy,:new,:edit,:update,:index]
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to  :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
  def index
    @blogs = Blog.all.order("created_at DESC").page(params[:page]).per(5)
  end

  def new

  end

  def create
    Blog.create(text: blog_params[:text],user_id: current_user.id)
  end

  def destroy
    blog = Blog.find(params[:id])
    blog.destroy if blog.user_id == current_user.id
  end
  def edit
    @blog = Blog.find(params[:id])
  end
  def update
    blog =Blog.find(params[:id])
    blog.update(blog_params) if blog.user_id == current_user.id
  end


  private
  def blog_params
    params.permit(:text)
  end
  def move_to_index
    redirect_to action: "index" unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  has_many   :blogs
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_blog.html.erb
<div class="row">
    <div class="col-s12-m6">
      <div class="card black darken-1">
        <div class="card-content white-text">
          <p><%= simple_format(blog.text + "メーン！") %></p>
          <style> 
          .card {
            width:60%;
            margin:20px  auto 0 auto;
            min-width:400px;
          }
          </style>
        </div>
        <% if user_signed_in? && current_user.id == blog.user_id %>
          <div class="card-action">
            <%= link_to '編集するメーン',"/blogs/#{blog.id}/edit", method: :get%>
            <%= link_to '削除するメーン', "/blogs/#{blog.id}", method: :delete %>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/blogs/create.html.erb
 <div class="contents row">
    <div class="success">
      <h3>
        サンキューメーン！！
      </h3>
      <a class="btn" href="/">投稿一覧へ戻るメーン</a>
    </div>
  </div>

app/views/blogs/destroy.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        削除したぜメーン！
      </h3>
      <a class="btn" href="/">投稿一覧へ戻るメーン！</a>
    </div>
  </div>

app/views/blogs/edit.html.erb
<div class="contents row">
    <%= form_for(@blog) do %>
      <h3>
        編集するぜメーン！
      </h3>
      <textarea cols="30" name="text" placeholder="text" rows="10"><%= @blog.text %></textarea>
      <input type="submit" value="SENT">
    <% end %>
  </div>

app/views/blogs/index.html.erb
<div class="contents row">
 <%= render @blogs %>
 
 <%= paginate(@blogs) %>
</div>

app/views/blogs/new.html.erb
<div class="contents row">
  <%= form_with(model: @blog,url: blogs_path,local: true) do %>
    <h3>
      投稿するぜメーン
    </h3>
    
    <textarea cols="30" name="text" placeholder="What's upメーン？" rows="10"></textarea>
    <input type="submit" value="SENT">
  <% end %>
</div>

app/views/blogs/update.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        サンキューメーン！！
      </h3>
      <a class="btn" href="/">投稿一覧へ戻るメーン</a>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nerimotherfax</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <style type="text/css" href="./style.css"></style>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
            
  
  </head>

  <body>
  <nav class="black">
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">練マザファックス</a>
        <% if user_signed_in? %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="/blogs/new">投稿するメーン？</a></li>
            <li><%= link_to "ログアウトするメーン？", destroy_user_session_path, method: :delete %></li>
          </ul>
        <% else %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><%= link_to "新規登録するメーン？", new_user_registration_path, class: 'post' %></li>
            <li><%= link_to "ログインするメーン？", new_user_session_path, class: 'post' %></li>
          </ul>
        <% end %>
      </div>
    </nav>

<style>
.nav-wrapper {
  padding-left:50px;
  padding-right:50px;
}
</style>
  
    <%= yield %>
  </body>
</html>